apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/DTS
  children:
  - name: zions-vsts-policy-microservice
    type: udm.Application
    children:
    - name: !value "app_version"
      type: udm.DeploymentPackage
      deployables:      
      - name: zions-vsts-policy-microservice0.xml
        type: file.File
        scanPlaceholders: true
        targetPath: '{{stage.path}}'
        createTargetPath: "true"
        file: !file "../service/service0.xml"
      - name: zions-ire-test-microservice-hold.jar
        type: file.File
        scanPlaceholders: false
        targetPath: '{{stage.path}}'
        createTargetPath: "true"
        file: !file "../../build/libs/zions-ire-test-microservice.jar"
      - name: zions-ire-test-microservice.exe.config
        type: file.File
        scanPlaceholders: false
        targetPath: '{{stage.path}}'
        createTargetPath: "true"
        file: !file "../service/service.exe.config"
      - name: zions-ire-test-microservice run install
        type: advcmd.Command
        command: |-
          mkdir {{deploy.path}}
          copy /Y {{stage.path}}\zions-ire-test-microservice-hold.jar {{deploy.path}}\zions-ire-test-microservice.jar
          copy /Y {{deploy.path}}\..\WinSW.NET4.exe {{deploy.path}}\zions-ire-test-microservice0.exe
          copy /Y {{stage.path}}\zions-ire-test-microservice0.xml {{deploy.path}}\zions-ire-test-microservice0.xml
          for /f "delims=" %%i in ('{{deploy.path}}\zions-ire-test-microservice0.exe status') do set status0=%%i
          if %status0%==NonExistent (
            {{deploy.path}}\zions-ire-test-microservice0.exe install
            {{deploy.path}}\zions-ire-test-microservice0.exe start 
          ) else (
            {{deploy.path}}\zions-ire-test-microservice0.exe restart
          )      
        createOrder: "62"
        destroyOrder: "42"
        alwaysRun: "true"
        noopOrder: "62"
        undoCommand: 'echo "No action needed for undoCommand"'