variables:
- group: 'XebiaLabs CLI (Prod)'

trigger:
  branches:
    include:
    - master
  paths:
    include:

    - 'zions-xlrtoado-event-microservice/*'
    
pool:
  name: On-Prem Production
  demands:
  - agent.computername -equals UTMVPI0144
  
 
stages:
- stage: Build
  jobs:
  - job: Build
#    workspace:
#      clean: none

    steps:
    - task: Zions.zions-vsts-build.tag-build-task.TagBuild@3
      displayName: 'Tag'
      inputs:
        OutputVariable: buildTag
        InitialVersionPrefix: 7.0.0
        WriteTag: true
    - script: |
        echo ##vso[task.setvariable variable=oBuildTag;isOutput=true]$(buildTag)
      name: 'oTag'

    - task: Gradle@2
      displayName: 'gradlew clean build updateBatJarVersion'
      inputs:
        gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew.bat'
        workingDirectory: '$(Build.SourcesDirectory)'
        options: '--no-daemon --no-scan -Pversion=$(buildTag) -Pqueue=default -Pcontext=microservices'
        tasks: 'clean zions-xlrtoado-event-microservice:build'
        publishJUnitResults: false

#     - task: BatchScript@1
#       displayName: 'XLW - xl-apps.yaml'
#       inputs:
#         filename: '$(Build.SourcesDirectory)\zions-xlrtoado-event-microservice\pipeline\xl.exe'
#         arguments: 'apply -f xl-apps.yaml --xl-deploy-url $(xld_cli_url) --xl-deploy-username $(xld_cli_user) --xl-deploy-password $(xld_cli_passwd) --values app_version=$(buildTag),xld_cli_user=$(xld_cli_user),xld_cli_passwd=$(xld_cli_passwd),svc_account_passwd=$(svc_account_passwd)'
#         workingFolder: $(Build.SourcesDirectory)\zions-xlrtoado-event-microservice\pipeline
#       continueOnError: false
#       enabled: true
      
    - task: Zions.ado-ext-release-status-control.XldApplyTask.XldApplyTask@0
      displayName: 'XLD Apply'
      inputs:
        xldFile: zions-xlrtoado-event-microservice\.pipeline\xl-apps.yaml
        xlValues: |
          app_version=$(buildTag)
          xld_cli_user=$[xl.user]
          xld_cli_passwd=$[xl.password]
          svc_account_passwd=$[svc_account_passwd]
      
- stage: Release
  dependsOn: Build
  jobs:
  - deployment: prod
    environment: Windows_Production
    variables:
      releaseTag: $[ stageDependencies.Build.Build.outputs['oTag.oBuildTag'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Zions.ado-ext-release-status-control.CreateReleaseTask.CreateReleaseTask@0
            displayName: 'Create Release'
            inputs:
              templateTitle: 'zions-xlrtoado-event-microservice - Master'
              releaseTitle: 'zions-xlrtoado-event-microservice - $(releaseTag)'
              releaseVariableSettings: 'deploymentPackage.name=$(releaseTag)'