variables:
- group: 'XebiaLabs CLI (Prod)'

trigger:
  branches:
    include:
    - master
  paths:
    include:

    - 'zions-xlrtoado-event-microservice/*'
    - 'zions-vsts-microservice/*'
    - 'zions-xlr-services/*'
    - 'zions-vsts-services/src/main/groovy/com/zions/vsts/services/build/*'
    
pool:
  name: On-Prem Production
  demands:
  - agent.computername -equals utlxa1846
  
 
stages:
- stage: Build
  jobs:
  - job: Build
#    workspace:
#      clean: none

    steps:
    - task: Zions.zions-vsts-build.tag-build-task.TagBuild@3
      displayName: 'Tag'
      inputs:
        OutputVariable: buildTag
        InitialVersionPrefix: 7.0.0
        WriteTag: true


    - bash: |
        sed -i -e 's/\r$//' gradlew
        chmod 777 $(Build.SourcesDirectory)/gradlew
        $(Build.SourcesDirectory)/gradlew --no-daemon --no-scan -PvaultResources=/app/Vault/resources -Pversion=$(buildTag) -Pqueue=default -Pcontext=microservices clean zions-xlrtoado-event-microservice:build zions-xlrtoado-event-microservice:dockerPushImage
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'gradlew clean build updateBatJarVersion'
#       inputs:
#         gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew'
#         workingDirectory: '$(Build.SourcesDirectory)'
#         options: '--no-daemon --no-scan -Pversion=$(buildTag) -Pqueue=default -Pcontext=microservices'
#         tasks: 'clean zions-xlrtoado-event-microservice:build zions-xlrtoado-event-microservice:dockerPushImage'
#         publishJUnitResults: false

#     - task: BatchScript@1
#       displayName: 'XLW - xl-deploy.yaml'
#       inputs:
#         filename: '$(Build.SourcesDirectory)\zions-xlrtoado-event-microservice\pipeline\xl.exe'
#         arguments: 'apply -f xl-deploy.yaml --xl-deploy-url $(xld_cli_url) --xl-deploy-username $(xld_cli_user) --xl-deploy-password $(xld_cli_passwd) --values app_version=$(buildTag),xld_cli_user=$(xld_cli_user),xld_cli_passwd=$(xld_cli_passwd),svc_account_passwd=$(svc_account_passwd)'
#         workingFolder: $(Build.SourcesDirectory)\zions-xlrtoado-event-microservice\pipeline
#       continueOnError: false
#       enabled: true
#       
#     - task: BatchScript@1
#       displayName: 'XLW - xl-release.yaml'
#       inputs:
#         filename: '$(Build.SourcesDirectory)\zions-xlrtoado-event-microservice\pipeline\xl.exe'
#         arguments: 'apply -f xl-release.yaml --xl-release-url $(xlr_cli_url) --xl-release-username $(xld_cli_user) --xl-release-password $(xld_cli_passwd) --values app_version=$(buildTag),xld_cli_user=$(xld_cli_user),xld_cli_passwd=$(xld_cli_passwd),svc_account_passwd=$(svc_account_passwd),xlr_scriptUserPassword=$(xlr_scriptUserPassword),release_name="zions-xlrtoado-event-microservice-$(buildTag)"'
#         workingFolder: $(Build.SourcesDirectory)\zions-xlrtoado-event-microservice\pipeline
#       continueOnError: true
#       enabled: true