# levels for loggers, e.g. "logging.level.org.springframework=DEBUG" (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
  level:
     org:
       springframework: WARN
     com:
       zions:
         vsts: DEBUG

#spring boot logging configuration
  file: policymanagement.log

#use spring boot whitelabel error page to see in browser client if you encounter a server error
error:
  whitelabel:
    enabled: true

#disable spring boot's auto-configuration for Apache Velocity
spring:
  velocity:
    enabled: false

# TFS connection properties
# test
#tfs:
#  url: http://utmsdev0487:8080/tfs
#  user: z091556
#  token: tqkjeiqplam3as6igdidjduljqz3z3vyqom6crrtszz7hhg7sika

# on prem
#tfs:
#  url: https://tfs.testqa.zionsbank.com
#  user: z091556
#  token: o5nxn5isv2tlekt4hdhezxodtslfs6mqi3e2hqoo25sd2zgd7d3a

tfs:
  url: https://eto-dev.visualstudio.com
  user: z091556
  token: emjfvuveeugbljidpareidxmya5zdvugt3gqp5ptidakh52ekq3q
  build:
    queue: default

# Specify port for Tomcat (default = 8080)
server:
  port: 9000

# Spring actuator
endpoints:
  enabled: false
  
#disable the automatic adding of the `X-Application-Context` HTTP header
management:
  add-application-context-header: false
  
# type map placeholder
type:
  map:
    resource:  dummy.json
  
name:
  map:
    resource:  namedummy.json
    
default:
  wit:
    name: Feature
    
cache:
  location: .\cache
  