# levels for loggers, e.g. "logging.level.org.springframework=DEBUG" (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
  level:
    org:
      springframework: WARN
    com:
      zions:
        vsts: DEBUG
        common: DEBUG

#spring boot logging configuration
  file: policymanagement.log

#use spring boot whitelabel error page to see in browser client if you encounter a server error
error:
  whitelabel:
    enabled: true

#disable spring boot's auto-configuration for Apache Velocity
spring:
  velocity:
    enabled: false
  main:
    web-application-type: NONE
    allow-bean-definition-overriding: true
  mail:
    host:  outboundrelay.cs.zionsbank.com
    port:  25
    properties:
      mail:
        smtp:
          connectiontimeout:  5000
          timeout:  5000
          writetimeout:  5000
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest          
email:
  recipient:
    addresses: DL-ReleaseEngineering@zionsbancorp.com,DL-ALMOps@zionsbancorp.com
  sender:
    address: DL-ReleaseEngineering@zionsbancorp.com
# TFS connection properties
tfs:
# test
#  url: https://dev.azure.com/eto-dev
#  user: z091556
#  token: emjfvuveeugbljidpareidxmya5zdvugt3gqp5ptidakh52ekq3q
# prod
  url: https://dev.azure.com/ZionsETO
  user: svc-cloud-vsbuildagent@zionsbancorporation.onmicrosoft.com
  token: hpwk4nbqnk4sm2fia5ww6ais4lvp2fiiu6zwvnbinbwf7akpxira
  project: dummy
  collection:
  build:
    queue: On-Prem Production
    use:
      template: true
    generic:
      name: generic
    properties:
      file: dts-re-build.properties
  release:
    use:
      template: false
    generic:
      name: template-release

# Specify port for Tomcat (default = 8080)
server:
  port: 9091

# Spring actuator
endpoints:
  enabled: false
  
#disable the automatic adding of the `X-Application-Context` HTTP header
management:
  add-application-context-header: false


email:
  recipient:
    address: SCMTeam@zionsbancorp.com

# type map placeholder
type:
  map:
    resource:  dummy.json
  
name:
  map:
    resource:  namedummy.json
    
external:
  name: External

default:
  wit:
    name: Feature

cache:
  location: .\cache

id:
  tracking:
    field: dummy
# Event registration properties
websocket:
# test
#  url: ws://utmvti0192:9000/ws
# prod
  url: ws://utlxa1846:9000/ws

# The path to the keystore containing the certificate
http:
  client:
    ssl:
      trust-store: classpath:keystore/zionsws.p12
# The password used to generate the certificate
      trust-store-password: changeit

  