# levels for loggers, e.g. "logging.level.org.springframework=DEBUG" (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
  level:
     org:
       springframework: WARN
     com:
       zions:
         vsts: DEBUG

#spring boot logging configuration
  file: policymanagement.log

#use spring boot whitelabel error page to see in browser client if you encounter a server error
error:
  whitelabel:
    enabled: true

#disable spring boot's auto-configuration for Apache Velocity
spring:
  velocity:
    enabled: false

# TFS connection properties
tfs:
  url: http://utmsdev0487:8080/tfs
  user: z091556
  token: tqkjeiqplam3as6igdidjduljqz3z3vyqom6crrtszz7hhg7sika

# Specify port for Tomcat (default = 8080)
server:
  port: 9000

# Spring actuator
endpoints:
  enabled: false
  
#disable the automatic adding of the `X-Application-Context` HTTP header
management:
  add-application-context-header: false
  