# levels for loggers, e.g. "logging.level.org.springframework=DEBUG" (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
  level:
     org:
       springframework: WARN
     com:
       zions:
         vsts: DEBUG

#spring boot logging configuration
  file: policymanagement.log

#use spring boot whitelabel error page to see in browser client if you encounter a server error
error:
  whitelabel:
    enabled: true

#disable spring boot's auto-configuration for Apache Velocity
spring:
  velocity:
    enabled: false

# TFS connection properties
tfs:
# test
#  url: https://eto-dev.visualstudio.com
#  user: z091556
#  token: emjfvuveeugbljidpareidxmya5zdvugt3gqp5ptidakh52ekq3q
# prod
  url: https://zionseto.visualstudio.com
  user: svc-cloud-vsbuildagent@zionsbancorporation.onmicrosoft.com
  token: i7lgdocpaar45qlx3wbmr5bfros6j6jhuxbjc7b5twucufn2w43a
  build:
    queue: default
    use:
      template: true
    generic:
      name: generic
    properties:
      file: dts-re-build.properties
  release:
    use:
      template: false
    generic:
      name: template-release

# Specify port for Tomcat (default = 8080)
server:
  port: 9000

# Spring actuator
endpoints:
  enabled: false
  
#disable the automatic adding of the `X-Application-Context` HTTP header
management:
  add-application-context-header: false

# spring mail properties
spring:
  mail:
    host:  outboundrelay.cs.zionsbank.com
    port:  25
    properties:
      mail:
        smtp:
          connectiontimeout:  5000
          timeout:  5000
          writetimeout:  5000

email:
  recipient:
    address: SCMTeam@zionsbancorp.com

# type map placeholder
type:
  map:
    resource:  dummy.json
  
name:
  map:
    resource:  namedummy.json
    
external:
  name: External

default:
  wit:
    name: Feature
    
cache:
  location: .\cache
  
id:
  tracking:
    field: dummy

  