---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Environments/DTS
  type: core.Directory
  children:
  - directory: zions-queue-pubsub-wit-microservice
    children:
    
    - name: Prod
      type: udm.Environment
      members:
      
      - Infrastructure/DTS/microservice/Prod
      
      dictionaries:
      - Environments/DTS/zions-queue-pubsub-wit-microservice/_Dictionaries/Prod_Dict
    - directory: _Dictionaries
      children:
      
      - name: Prod_Dict
        type: udm.Dictionary
        entries:
          
          stage.path: d:\app\azure\_work\zions-queue-pubsub-wit-microservice
          deploy.path: d:\app\azure\services\zions-queue-pubsub-wit-microservice
          
          ws.url: <no value>
          
          tfs.url: https://dev.azure.com/zionseto