---
apiVersion: xl-release/v1
kind: Release
spec:
  name: !format "zions-queue-pubsub-wit-microservice %app_version%"
  template: !format DTS/zions-queue-pubsub-wit-microservice - Master
  variables:
    deploymentPackage.name: !value "app_version"