---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Environments/DTS
  type: core.Directory
  children:
  - directory: zions-vsts-parent-change-microservice
    children:
    
    - name: Prod
      type: udm.Environment
      members:
      - Infrastructure/DTS/microservice/Prod
      dictionaries:
      - Environments/DTS/zions-vsts-parent-change-microservice/_Dictionaries/Prod_Dict
    - directory: _Dictionaries
      children:
      
      - name: Prod_Dict
        type: udm.Dictionary
        entries:
          
          stage.path: d:\app\azure\_work\zions-vsts-parent-change-microservice
          deploy.path: d:\app\azure\services\zions-vsts-parent-change-microservice
          
          ws.url: <no value>
          
          tfs.collection: zionseto