config:
    inputFields:
        - 'Custom.Complexity'
        - 'Custom.Frequency'
    outputField: 'Custom.Impact'
    mapname: 'impactMap.json'
    

tfs.outputMapUID:  Zions/zions-color-form-control2/Data/Scopes/Default/Current/Collections/%24settings/Documents/outputMap 
doc.resource.locations: file:///C:/Resources/
server.port: "9094"
websocket.url: ws://localhost/ws
http.client.ssl.trust-store: classpath:keystore/zionsws.p12
http.client.ssl.trust-store-password: changeit
tfs.project.includes: ALMOpsTest
tfs.url:  "https://dev.azure.com"
tfs.collection:  "zionseto" 
spring.main.allow-bean-definition-overriding: "true"
spring.rabbitmq.host: localhost
spring.rabbitmq.port: "5672"
spring.main.web-application-type: NONE
spring.mail.host: outboundrelay.cs.zionsbank.com
spring.mail.port: "25"
email.recipient.addresses: DL-ReleaseEngineering@zionsbancorp.com,DL-ALMOps@zionsbancorp.com
email.sender.address: DL-ReleaseEngineering@zionsbancorp.com