apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/DTS
  type: core.Directory
  children:
  - name: zions-vsts-setcolor-microservice
    type: udm.Application
    children:
    - name: !value "app_version"
      type: udm.DeploymentPackage
      deployables:
      
      - name: zions-vsts-setcolor-microservice-queuing.xml
        type: file.File
        scanPlaceholders: true
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../service/queue.xml"
      - name: zions-queuing-microservice.jar
        type: file.File
        scanPlaceholders: false
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../../../zions-queuing-microservice/build/libs/zions-queuing-microservice.jar"
      - name: zions-vsts-setcolor-microservice-queuing.exe
        type: file.File
        scanPlaceholders: false
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../service/queue.exe"
      - name: zions-vsts-setcolor-microservice-queuing.exe.config
        type: file.File
        scanPlaceholders: false
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../service/queue.exe.config"
      - name: run queuing install
        type: advcmd.Command
        command: |-
          {{deploy.path}}/zions-vsts-setcolor-microservice-queuing.exe uninstall
          {{deploy.path}}/zions-vsts-setcolor-microservice-queuing.exe install
          {{deploy.path}}/zions-vsts-setcolor-microservice-queuing.exe start
        createOrder: "61"
        destroyOrder: "41"
        alwaysRun: "true"
        noopOrder: "61"
        undoCommand: 'echo "No action needed for undoCommand"'
      
      - name: zions-vsts-setcolor-microservice.xml
        type: file.File
        scanPlaceholders: true
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../service/service.xml"
      - name: zions-vsts-setcolor-microservice.jar
        type: file.File
        scanPlaceholders: false
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../../build/libs/zions-vsts-setcolor-microservice.jar"
      - name: zions-vsts-setcolor-microservice.exe
        type: file.File
        scanPlaceholders: false
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../service/service.exe"
      - name: zions-vsts-setcolor-microservice.exe.config
        type: file.File
        scanPlaceholders: false
        targetPath: '{{deploy.path}}'
        createTargetPath: "true"
        file: !file "../service/service.exe.config"
      - name: run install
        type: advcmd.Command
        command: |-
          {{deploy.path}}/zions-vsts-setcolor-microservice.exe uninstall
          {{deploy.path}}/zions-vsts-setcolor-microservice.exe install
          {{deploy.path}}/zions-vsts-setcolor-microservice.exe start
        createOrder: "62"
        destroyOrder: "42"
        alwaysRun: "true"
        noopOrder: "62"
        undoCommand: 'echo "No action needed for undoCommand"'