apiVersion: xl/v2
kind: Blueprint

metadata:
  name: dts-service-connection
  description: |
    Blueprint for creating ADO service connections.
  author: XebiaLabs
  version: 2.0
  instructions: none

spec:
  parameters:
  - name: ConnName
    type: Input
    prompt: Enter a name for the service connection.
    
  - name: ConnectTo
    type: Select
    options:
      - XL Deploy
      - Nexus IQ
      - Other   
    prompt: Select the service for which to create the connection.
    
  - name: Projects
    type: Input
    prompt: Enter comma delimited list of ADO projects (or 'all').
    
  - name: TargetEnv
    type: Select
    options:
      - Production
      - Test   
    default: Production
    prompt: Select the environment for the connection.
    


  files:
  - path: serviceconns/xldeploy-svcconn.yaml.tmpl
    writeIf: !expr "ConnectTo == 'XL Deploy'"
  - path: serviceconns/nexusiq-svcconn.yaml.tmpl
    writeIf: !expr "ConnectTo == 'Nexus IQ'"
  - renameTo: ado-svcconn.yaml
