trigger: none

pool:
  name: Default
  demands:
  - agent.computername -equals UTMVPI0144

steps:
- task: Gradle@2
  displayName: 'gradlew clean build'
  inputs:
    options: '--no-scan -Pqueue=default -Pcontext=all -PbuildType=ci'
    tasks: 'clean build'
    publishJUnitResults: false