name: $(date:yyyyMMdd)$(rev:.rrr)

parameters:
- name: pool_name
  displayName: Pool Name
  type: string
  default: On-Prem Production
  values:
  - On-Prem Production
  - On-Prem DR
  - Rancher - demo

trigger: none

stages:
- stage: Build
  jobs:
  # Job: build - checkout, compile
  - job: build
    pool:
      name: ${{ parameters.pool_name }}
      demands:
        #- agent.computername -equals UTMVPI0144
        # - agent.os -equals Linux
        - agent.computername -equals utlxa1846
    workspace:
      # all - delete these dirs: _work/1, _work/1/a, _work/1/TestResults, _work\1\b, _work\1\s
      # resources - delete these dirs: _work/1/a, _work/1/TestResults, _work\1\s
      # outputs - delete these dirs: _work/1/a, _work/1/TestResults, _work\1\b
      clean: resources 
    steps:
    - task: Gradle@2
      displayName: 'Gradle: gradlew clean build'
      inputs:
        options: '-Pqueue=default -Pcontext=all -PbuildType=ci'
        tasks: 'clean build'
        publishJUnitResults: false