trigger: none

pool:
  name: On-Prem Production
  demands:
  - agent.computername -equals UTMVPI0144
  - java

steps:
- task: Gradle@2
  displayName: 'gradlew clean build'
  inputs:
    options: '--no-scan -Pqueue=default -Pcontext=all'
    tasks: 'clean build'
    publishJUnitResults: false