variables:
- group: 'XebiaLabs CLI (Prod)'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'none/*'
    
  
 
#Your build pipeline references an undefined variable named ‘buildTag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Tag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘buildTag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Tag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: On-Prem Production
      demands:
      #- agent.computername -equals UTMVPI0144
      - agent.os -equals Linux
      
#    workspace:
#      clean: none

    steps:
    - task: Zions.zions-vsts-build.tag-build-task.TagBuild@3
      displayName: 'Tag Pending'
      inputs:
        OutputVariable: buildTag
        InitialVersionPrefix: 7.1.0

    - task: Gradle@2
      displayName: 'Gradle: gradlew clean build updateBatJarVersion'
      inputs:
        gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew'
        workingDirectory: '$(Build.SourcesDirectory)'
        #options: '--no-scan -Pversion=$(buildTag) -Pqueue=default -Pcontext=pipeline'
        options: '--no-scan --refresh-dependencies -Pcontext=pipeline'
        tasks: 'clean build zions-common:uploadArchives zions-vsts-service:uploadArchives zions-common-data:uploadArchives'
        publishJUnitResults: false

 
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/TEST-*.xml'
      enabled: false

#     - task: BatchScript@1
#       displayName: 'Run Publish Tests'
#       inputs:
#         filename: '$(Build.SourcesDirectory)\zions-pipeline-cli\java.bat'
#         arguments: '-Dspring.profiles.active=spock -jar $(System.ArtifactsDirectory)/zions-pipeline-cli/build/libs/zions-pipeline-cli.jar syncTesting --tfs.url=https://dev.azure.com/zionseto --report.search.dir=$(Build.SourcesDirectory) --tfs.project=DTS --ado.area.path=DTS\ReleaseEngineering --ado.iteration.path=DTS --cache.location=$(Build.SourcesDirectory)/spockcache --main.tag=pipeline --plan.name=pipeline-release-$(Tag)'
#       continueOnError: true
#       enabled: true

     
