variables:
- group: 'XebiaLabs CLI (Prod)'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'zions-common/*'
    - 'zions-common-data/*'
    - 'zions-vsts-services/*'
    - 'zions-vsts-microservice/*'
    
  
 
#Your build pipeline references an undefined variable named ‘buildTag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Tag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘buildTag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Tag’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: On-Prem Production
      demands:
      - agent.computername -equals UTMVPI0144
#    workspace:
#      clean: none

    steps:
    - task: Zions.zions-vsts-build.tag-build-task.TagBuild@3
      displayName: 'Tag Pending'
      inputs:
        OutputVariable: buildTag
        InitialVersionPrefix: 7.1.0

    - task: Gradle@2
      displayName: 'gradlew clean build uploadArchives'
      inputs:
        gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew.bat'
        workingDirectory: '$(Build.SourcesDirectory)'
        options: '--no-scan -Pversion=$(buildTag) -Pqueue=default -Pcontext=nexus'
        tasks: 'clean build zions-common:uploadArchives zions-vsts-service:uploadArchives zions-common-data:uploadArchives zions-vsts-microservice:uploadArchives'
        publishJUnitResults: false


 
      
