select reference_id, about, text from (
WITH filtered AS (
SELECT DISTINCT T1.PROJECT_NAME,
       T1.REFERENCE_ID,
       T1.NAME AS URL1_title,
       T1.URL AS URL1,
       T1.REQUIREMENT_TYPE,
       LT1.LINK_TYPE,
       T2.REFERENCE_ID AS REFERENCE_ID1,
       T2.NAME AS URL2_title,
       T2.URL AS URL2
FROM RIDW.VW_REQUIREMENT T1
INNER JOIN RIDW.VW_REQUIREMENT_HIERARCHY LT1
ON (T1.REQUIREMENT_ID = LT1.SUCC_REQUIREMENT_ID) --AND LT1.LINK_TYPE = 'Satisfaction'
  INNER JOIN RIDW.VW_REQUIREMENT T2
  ON (LT1.PRED_REQUIREMENT_ID = T2.REQUIREMENT_ID) AND T2.PROJECT_ID = 19  AND T2.ISSOFTDELETED = 0
      LEFT OUTER JOIN RICALM.VW_RQRMENT_STRING_EXT T3
    ON T3.REQUIREMENT_ID=T1.REQUIREMENT_ID AND T3.NAME='DMZ Name'
WHERE T1.PROJECT_ID = 19  AND
(  T1.REQUIREMENT_TYPE = 'TCS Data Element' AND
  ( LOWER(T3.VAL) LIKE '%dmz-040-r2-facility master-01-add-04-shaw%' ) 
) AND
TRUNC(T1.REC_DATETIME) <= TO_DATE(:endDate,'mm/dd/yyyy') AND
T1.ISSOFTDELETED = 0 AND
(T1.REQUIREMENT_ID <> -1 AND T1.REQUIREMENT_ID IS NOT NULL) AND
(T2.REQUIREMENT_ID <> -1 AND T2.REQUIREMENT_ID IS NOT NULL)
)
select REFERENCE_ID as reference_id, url1 as about, URL1_title as text from filtered
union
select REFERENCE_ID1, url2, URL2_title from filtered )