SELECT T1.REFERENCE_ID as reference_id,
  T1.URL as about,
  T1.Primary_Text as text
FROM RIDW.VW_REQUIREMENT T1
LEFT OUTER JOIN RIDW.VW_REQUICOL_REQUIREMENT_LOOKUP LT1
  ON (T1.REQUIREMENT_ID = LT1.REQUIREMENT_ID)
LEFT OUTER JOIN RIDW.VW_REQUIREMENT_COLLECTION T2
  ON LT1.REQUIREMENT_COLLECTION_ID = T2.REQUIREMENT_COLLECTION_ID
WHERE T1.PROJECT_ID = 19  AND
  LT1.REQUIREMENT_COLLECTION_ID = 5602 AND
  T1.REC_DATETIME < TO_DATE(:endDate,'mm/dd/yyyy') AND
T1.ISSOFTDELETED = 0 AND
(T1.REQUIREMENT_ID <> -1 AND T1.REQUIREMENT_ID IS NOT NULL)