SELECT DISTINCT T1.REFERENCE_ID,
       T2.REFERENCE_ID AS REFERENCE_ID1,
       T2.URL AS URL2,
       T2.NAME AS MODULE_NAME
FROM RIDW.VW_REQUIREMENT T1
INNER JOIN RIDW.VW_REQUICOL_REQUIREMENT_LOOKUP LT1
ON (T1.REQUIREMENT_ID = LT1.REQUIREMENT_ID)
  INNER JOIN RIDW.VW_REQUIREMENT_COLLECTION T2
  ON (T2.REQUIREMENT_COLLECTION_ID = LT1.REQUIREMENT_COLLECTION_ID) AND T2.PROJECT_ID = 19  AND T2.ISSOFTDELETED = 0
    LEFT OUTER JOIN RICALM.VW_RQRMENT_ENUMERATION T3
    ON T3.REQUIREMENT_ID=T1.REQUIREMENT_ID AND T3.NAME='Release'
WHERE T1.PROJECT_ID = 19  AND
(  T3.LITERAL_NAME IN ('Consumer Lending','One DOT One') 
) AND
T1.ISSOFTDELETED = 0 AND
(T1.REQUIREMENT_ID <> -1 AND T1.REQUIREMENT_ID IS NOT NULL) AND
(T2.REQUIREMENT_COLLECTION_ID <> -1 AND T2.REQUIREMENT_COLLECTION_ID IS NOT NULL) ORDER BY T1.REFERENCE_ID asc,
         T2.REFERENCE_ID desc