SELECT DISTINCT T1.PROJECT_NAME,
       T1.REFERENCE_ID,
       T1.NAME AS URL1_title,
       T1.URL AS URL1,
       T2.REFERENCE_ID AS module_id,
       T2.NAME AS MODULE_NAME,
       T2.URL AS URL2
FROM RIDW.VW_REQUIREMENT T1
INNER JOIN RIDW.VW_REQUICOL_REQUIREMENT_LOOKUP LT1
ON (T1.REQUIREMENT_ID = LT1.REQUIREMENT_ID)
  INNER JOIN RIDW.VW_REQUIREMENT_COLLECTION T2
  ON (T2.REQUIREMENT_COLLECTION_ID = LT1.REQUIREMENT_COLLECTION_ID) AND T2.PROJECT_ID = 19  AND T2.ISSOFTDELETED = 0
WHERE T1.PROJECT_ID = 19 
 AND
T1.ISSOFTDELETED = 0 AND
(T1.REQUIREMENT_ID <> -1 AND T1.REQUIREMENT_ID IS NOT NULL) AND
(T2.REQUIREMENT_COLLECTION_ID <> -1 AND T2.REQUIREMENT_COLLECTION_ID IS NOT NULL)