config:
    gateways:
        -
            id: 'g0'
            nbrInputs: 128
            nbrOutputs: 128
        -
            id: 'g1'
            nbrInputs: 128
            nbrOutputs: 128
            
    projects:
        -
            name: 'DTS'
            types:
              - "Feature"
              - "User Story"
              - "Task"
            states:
              - Active
              - Closed
 
        -
            name: 'DigitalBanking'
            types: 
              - "User Story"
              - "Task"
            states:
              - Active
              - Closed
              
        -
            name: 'Sandbox'
            types:
              - "Feature"
              - "User Story"
              - "Task"
            states:
              - Active
              - Closed
                 
        -
            name: 'default'
            types:
              - ""
            states:
              - Active
              - Closed
              
doc.resource.locations: file:///C:/Resources/
server.port: "9094"
websocket.url: ws://localhost/ws

http.client.ssl.trust-store: classpath:keystore/zionsws.p12
http.client.ssl.trust-store-password: changeit
tfs.project.includes: ALMOpsTest
tfs.url:  "https://dev.azure.com"
tfs.collection:  "zionseto" 
spring.main.allow-bean-definition-overriding: "true"
spring.rabbitmq.host: localhost
spring.rabbitmq.port: "5672"
spring.main.web-application-type: NONE
spring.mail.host: outboundrelay.cs.zionsbank.com
spring.mail.port: "25"
email.recipient.addresses: DL-ReleaseEngineering@zionsbancorp.com,DL-ALMOps@zionsbancorp.com
email.sender.address: DL-ReleaseEngineering@zionsbancorp.com