---

# Updated 2021-02-23 06:28:00.643264679 -0700 MST m=+1.291001721
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Environments/DTS
  type: core.Directory
  children:
  - directory: zions-pipeline-execution-microservice
    children:
    - name: Prod
      type: udm.Environment
      members:
      - Infrastructure/DTS/microservice/Prod
      dictionaries:
      - Environments/DTS/zions-pipeline-execution-microservice/_Dictionaries/Prod_Dict
    - directory: _Dictionaries
      children:
      - name: Prod_Dict
        type: udm.Dictionary
        entries:
          stage.path: d:\app\azure\_work\zions-pipeline-execution-microservice
          deploy.path: d:\app\azure\services\zions-pipeline-execution-microservice
          ws.url: <no value>
          tfs.url: https://dev.azure.com/zionseto          
          spring.profile: default