---
apiVersion: xl-release/v1
kind: Release
spec:
  name: !format "zions-pipeline-execution-microservice %app_version%"
  template: !format DTS/zions-pipeline-execution-microservice - Master
  variables:
    deploymentPackage.name: !value "app_version"